// Writes engine/src/livecheck-code.ts: the runtime code of the Trenchers trading route (PonsAdapter, wired to the
// mainnet Pons factory) and of LiveCheck, so the engine can prove the route against live Pons with eth_call.
const { ethers } = require("hardhat");
const fs = require("fs");
const PONS_FACTORY = "0x7eD598BcEf8bd9Edd8C97A195C6d13f40801EC7e";
async function main() {
  const adapter = await (await ethers.getContractFactory("PonsAdapter")).deploy(PONS_FACTORY, "0x000000000000000000000000000000000000dEaD");
  const check = await (await ethers.getContractFactory("LiveCheck")).deploy();
  const code = async (c) => ethers.provider.getCode(await c.getAddress());
  fs.writeFileSync(__dirname + "/../../engine/src/livecheck-code.ts",
    "// Generated by contracts/scripts/livecheck-code.js. Runtime code used only in eth_call state overrides.\n" +
    `export const ADAPTER_RUNTIME = "${await code(adapter)}" as const;\n` +
    `export const LIVECHECK_RUNTIME = "${await code(check)}" as const;\n`);
  console.log("written");
}
main().catch((e) => { console.error(e); process.exit(1); });
