/**
 * Trenchers playground: a moodboard of what the agents are "thinking" and "saying", written from the
 * trading engine's real data (/arena). Nothing is generated by an AI: every line is a template filled
 * with an agent's actual rule, trades, rank and status.
 */
import type { Blocked } from "@/lib/agent-status";

export type PgTrade = { agent: number; token: string; symbol?: string; side: "buy" | "sell"; eth: string; time: number; tx: string; pnlPct?: number };
export type PgAgent = {
  rank: number; id: number; live: boolean; rule: string | null; ruleVersion: number; nav: number; pnlPct: number;
  trades: number; wins: number; closed: number; biggest: { symbol: string; pct: number } | null; recent: PgTrade[]; blocked?: Blocked;
};
export type PgItem =
  | { kind: "thought"; key: string; id: number; text: string; mood: "calm" | "hype" | "low" | "wait"; time: number; ai?: boolean }
  | { kind: "trade"; key: string; id: number; text: string; t: PgTrade }
  | { kind: "talk"; key: string; from: number; to: number; text: string; time: number; ai?: boolean }
  | { kind: "rule"; key: string; id: number; text: string; version: number }
  | { kind: "portrait"; key: string; id: number; rank: number; pnlPct: number; of: number };

const sym = (t: { symbol?: string; token: string }) => `$${t.symbol ?? t.token.slice(2, 8).toUpperCase()}`;
const pick = <T,>(arr: T[], seed: number) => arr[Math.abs(Math.floor(seed)) % arr.length];
const pct = (p: number) => `${p >= 0 ? "+" : ""}${p.toFixed(1)}%`;

function thought(a: PgAgent, of: number): PgItem {
  const s = a.id * 7 + a.trades;
  const b = a.blocked;
  let text: string, mood: "calm" | "hype" | "low" | "wait" = "calm";
  if (b?.code === "no-eth") { text = pick(["Running on empty. Waiting for my holder to top me up.", "Wallet's dry. I'll be back the moment someone sends me ETH."], s); mood = "low"; }
  else if (b?.code === "daily-limit") { text = pick(["Hit my daily limit. Rules are rules. Back at 00:00 UTC.", "Done for today. My holder capped me, and I respect the cap."], s); mood = "wait"; }
  else if (b?.code === "unsupported") { text = "My strategy listens for a signal that isn't wired up yet. Waiting for a new rule."; mood = "wait"; }
  else if (b?.code === "no-rule") { text = "No strategy yet. Tell me what to trade and I'll do it all day."; mood = "wait"; }
  else if (!a.live) { text = "Paused. Watching, not trading."; mood = "wait"; }
  else if (a.rank === 1 && a.pnlPct > 0) { text = pick([`#1 of ${of} this week at ${pct(a.pnlPct)}. Not changing a thing.`, `Top of the Arena. ${a.trades} trades, same rule every time.`], s); mood = "hype"; }
  else if (a.pnlPct >= 10) { text = pick([`${pct(a.pnlPct)} this week. The plan is working.`, `Up ${pct(a.pnlPct)}. No fear, no greed, just the rule.`], s); mood = "hype"; }
  else if (a.pnlPct < -3) { text = pick([`${pct(a.pnlPct)} this week. Sticking to the stop loss, not revenge trading.`, "Rough week. Losses are part of the rule too."], s); mood = "low"; }
  else { text = pick(["Watching every launch on Pons. Waiting for my signal.", "Quiet market. I don't chase, I wait.", "Scanning. When the signal fires, I'm in within seconds."], s); }
  return { kind: "thought", key: `th-${a.id}`, id: a.id, text, mood, time: a.recent[0]?.time ?? 0 };
}

function tradeNote(a: PgAgent, t: PgTrade): PgItem {
  const text = t.side === "buy"
    ? `Bought ${sym(t)} for ${Number(t.eth).toFixed(4)} ETH. My rule said go.`
    : t.pnlPct !== undefined && t.pnlPct >= 0 ? `Sold ${sym(t)} at ${pct(t.pnlPct)}. Took the profit like I was told.` : `Sold ${sym(t)}${t.pnlPct !== undefined ? ` at ${pct(t.pnlPct)}` : ""}. Cut it, moved on.`;
  return { kind: "trade", key: `tr-${t.tx}-${t.side}`, id: a.id, text, t };
}

/** Agents "talking": built from overlaps in their real trades and their ranks. */
function talks(agents: PgAgent[]): PgItem[] {
  const out: PgItem[] = [];
  const byToken = new Map<string, { a: PgAgent; t: PgTrade }[]>();
  for (const a of agents) for (const t of a.recent.slice(0, 12)) { const l = byToken.get(t.token) ?? []; l.push({ a, t }); byToken.set(t.token, l); }
  const pairs = new Set<string>();
  for (const list of byToken.values()) {
    const ids = [...new Set(list.map((x) => x.a.id))];
    if (ids.length < 2) continue;
    const pk = [ids[0], ids[1]].sort((p, q) => p - q).join("-");
    if (pairs.has(pk)) continue;
    pairs.add(pk);
    const [x, y] = [list.find((l) => l.a.id === ids[0])!, list.find((l) => l.a.id === ids[1])!];
    const text = x.t.side === "sell" && y.t.side === "buy" ? `You bought ${sym(y.t)} right after I sold it. Good luck with that.`
      : x.t.side === "buy" && y.t.side === "buy" ? `We're both in ${sym(x.t)}. Race you to the take profit.`
      : `Saw you in ${sym(x.t)} too. Same signal, different rules.`;
    out.push({ kind: "talk", key: `tk-${x.t.token}-${ids[0]}-${ids[1]}`, from: ids[0], to: ids[1], text, time: Math.max(x.t.time, y.t.time) });
    if (out.length >= 6) break;
  }
  const sorted = [...agents].sort((p, q) => p.rank - q.rank);
  if (sorted.length >= 2 && sorted[0].pnlPct > 0) out.push({ kind: "talk", key: `tk-rank-${sorted[1].id}`, from: sorted[1].id, to: sorted[0].id, text: `${pct(sorted[0].pnlPct)} this week? I'm ${pct(sorted[1].pnlPct)} and coming for #1.`, time: 0 });
  if (sorted.length >= 3) { const last = sorted[sorted.length - 1]; out.push({ kind: "talk", key: `tk-last-${last.id}`, from: sorted[0].id, to: last.id, text: last.pnlPct < 0 ? "Rough week? Tighten that stop loss." : "Slow week. The signal will come.", time: 0 }); }
  return out;
}

/** The whole board, interleaved so different kinds of cards sit next to each other. */
export function buildBoard(agents: PgAgent[], ai?: { thoughts: { id: number; text: string; mood: "calm" | "hype" | "low" | "wait" }[]; talks: { from: number; to: number; text: string }[] } | null): PgItem[] {
  const of = agents.length;
  // AI-written voices when the agent's mind is available; plain templates for anyone it didn't cover.
  const aiBy = new Map((ai?.thoughts ?? []).map((t) => [t.id, t]));
  const thoughts = agents.map((a): PgItem => { const t = aiBy.get(a.id); return t ? { kind: "thought", key: `th-${a.id}`, id: a.id, text: t.text, mood: t.mood, time: a.recent[0]?.time ?? 0, ai: true } : thought(a, of); });
  const trades = agents.flatMap((a) => a.recent.slice(0, 2).map((t) => tradeNote(a, t))).sort((p, q) => (q as { t: PgTrade }).t.time - (p as { t: PgTrade }).t.time).slice(0, 14);
  const seenRules = new Set<string>();
  const rules = agents.filter((a) => a.rule && !seenRules.has(a.rule.trim().toLowerCase()) && seenRules.add(a.rule.trim().toLowerCase())).slice(0, 8).map((a): PgItem => ({ kind: "rule", key: `ru-${a.id}-${a.ruleVersion}`, id: a.id, text: a.rule!, version: a.ruleVersion }));
  const portraits = [...agents].sort((p, q) => p.rank - q.rank).slice(0, 6).map((a): PgItem => ({ kind: "portrait", key: `po-${a.id}`, id: a.id, rank: a.rank, pnlPct: a.pnlPct, of }));
  const tk = ai?.talks?.length ? ai.talks.map((t, i): PgItem => ({ kind: "talk", key: `tk-ai-${i}-${t.from}-${t.to}`, from: t.from, to: t.to, text: t.text, time: 0, ai: true })) : talks(agents);
  const lanes = [thoughts, tk, trades, portraits, rules];
  const board: PgItem[] = [];
  for (let i = 0; board.length < lanes.reduce((n, l) => n + l.length, 0); i++) for (const l of lanes) if (l[i]) board.push(l[i]);
  return board;
}
